### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by AmericaToday** [jstar88/opbe#10]
dont work on my version i get 

<br />
<b>Fatal error</b>:  Call to undefined method Fleet::addShipType() in <b>C:\xampp\htdocs\darkspa\includes\classes\missions\calculateAttack.php</b> on line <b>81</b><br />

**Comment by jstar88** [comment]
Seems like you didn't updated to last versione the classe fleet.php

**Comment by AmericaToday** [comment]
yes sorry it was my fault ^^ but i had to update some parts for 1.7.3 as i got some errors ^^

**Comment by AmericaToday** [comment]
By the way when i change your basic code 
 $attTech = $player['military_tech'] + $player['factor']['Attack'] / WEAPONS_TECH_INCREMENT_FACTOR;
$shieldTech = $player['shield_tech'] + $player['factor']['Shield'] / SHIELDS_TECH_INCREMENT_FACTOR;
$defenceTech = $player['defence_tech'] + $player['factor']['Defensive'] / ARMOUR_TECH_INCREMENT_FACTOR;
in 
$attTech = $player['factor']['Attack'] * 100 ;    
$shieldTech = $player['factor']['Shield'] * 100;
$defTech = $player['factor']['Defensive'] * 100;

i get this
Friday 6th of March 2015 04:05:20 PM exception 'Exception' with message 'negative prob' in C:\xampp\htdocs\darkspa\includes\libs\opbe\combatObject\ShipsCleaner.php:69 Stack trace: #0 C:\xampp\htdocs\darkspa\includes\libs\opbe\models\ShipType.php(210): ShipsCleaner->start() #1 C:\xampp\htdocs\darkspa\includes\libs\opbe\models\Fleet.php(171): ShipType->cleanShips() #2 C:\xampp\htdocs\darkspa\includes\libs\opbe\models\Player.php(158): Fleet->cleanShips() #3 C:\xampp\htdocs\darkspa\includes\libs\opbe\models\PlayerGroup.php(117): Player->cleanShips() #4 C:\xampp\htdocs\darkspa\includes\libs\opbe\core\Round.php(115): PlayerGroup->cleanShips() #5 C:\xampp\htdocs\darkspa\includes\libs\opbe\core\Battle.php(77): Round->startRound() #6 [internal function]: Battle->startBattle() #7 C:\xampp\htdocs\darkspa\includes\libs\opbe\utils\DebugManager.php(57): call_user_func_array(Array, Array) #8 C:\xampp\htdocs\darkspa\includes\classes\missions\calculateAttack.php(123): DebugManager::{closure}() #9 C:\xampp\htdocs\darkspa\includes\classes\missions\MissionCaseAttack.php(155): calculateAttack(Array, Array, '30', '10') #10 C:\xampp\htdocs\darkspa\includes\classes\class.FlyingFleetHandler.php(82): MissionCaseAttack->TargetEvent() #11 C:\xampp\htdocs\darkspa\includes\FleetHandler.php(40): FlyingFleetHandler->run() #12 C:\xampp\htdocs\darkspa\includes\common.php(126): require('C:\\xampp\\htdocs...') #13 C:\xampp\htdocs\darkspa\game.php(35): require('C:\\xampp\\htdocs...') #14 {main} $_POST = $_GET =

**Comment by AmericaToday** [comment]
never mind used constant instead of the * 100 and its working now

**Comment by jstar88** [comment]
almost yes, use something like 

getPlayersLostShips($report->getRound(i)->getAfterBattleDefenders(),$report->getRound(i+1)->getAfterBattleDefenders()) 

that function is inside BattleReport.php
