### ISSUE TITLE
How to apply engine?

### ISSUE THREAD

**Issue by noonn** [jstar88/opbe#11]
Hi~
The battle enging is very good.
And, How to apply this code in 2moons sources?
My 2moons version is 1.3.5...
Please Some teach to me for apply source?

**Comment by jstar88** [comment]
Currently there is not 1.3.5 version. You should edit calculateattack.php as you need

**Comment by noonn** [comment]
Please Can you edit calculateattack.php.php?
i can not edit ㅠㅠ.

**Comment by jstar88** [comment]
I'm sorry but i don't really know how is 1.3.5. Anyway trust me, all version are really similar except some array indexes.. 
try to check differences between 1.6 and 1.3.5 original php file and then apply these changes to the implementation. Regards

**Comment by noonn** [comment]
My english is no good. sorry.^^
thank you very much for your interest to me..
appreciate your enthusiasm .
My 2moons 1.3 ~ 1.3.5 mixing. but  I thinks to same code.

Wait for you.
Thanks.^^
