### ISSUE TITLE
Var request

### ISSUE THREAD

**Issue by AmericaToday** [jstar88/opbe#12]
Hello what should i use as code to take an info from my db ?

+- line 256 you have this
$fleet = $player->getFleet($idFleet);
 if ($fleet->existShipType($idShipType)) //if there are some ships of this type
                {

i want to add on this $car = $playerGroup->getPlayer($info['player']['id']['academy_1103']; but i get an eror 

Kind regards for help

**Comment by jstar88** [comment]
this engine doesn't use any database, seems that you are trying to get the player with 
   `$info['player']['id']['academy_1103']`
You must assert that this player exist in the engine with 
   `$playerGroup->existPlayer($info['player']['id']['academy_1103'])`

Anyway this id not a bug..
