### ISSUE TITLE
Something battle fault.

### ISSUE THREAD

**Issue by noonn** [jstar88/opbe#18]
This is 2moons.
I thanks. this battle is attacker win.
But, Something wrong  like this ( draw )

------------------------------------
Attacker
250% - 250% - 250%
Avatar 3

Defender
80% - 120% - 100%
Missile Launcher 196
Light Laser Turret 14
Heavy Laser Turret 31
Gauss Cannon 1
Ion Cannon 1
Plasma Cannon 7
Small Shield Dome 1
Large Shield Dome 1

---- result of battle ----
The battle ended in a draw.

**Comment by jstar88** [comment]
the battle end with a win for the attacker, i tried.
What u see at end of battle are the defenses rebuilt.
