### ISSUE TITLE
i found something..

### ISSUE THREAD

**Issue by noonn** [jstar88/opbe#19]
I found a little problem.
The Heavy Cargo is destroyed by Shield Dome in round two.

** round2 Heavy Cargo 49
** round3 Heavy Cargo 48

Battle report this.
http://testopbe.altervista.org/CombatReport.php?raport=eb8fbada530a322a07337f982ab07cce

**Comment by jstar88** [comment]
ah, it's not destroyed by the shield dome.. The heavy cargo was already damaged and each round a ship has a probability to explode, ogame work like this :)
