### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by mrmd** [jstar88/opbe#20]
In the current '2Moons 1.7.2' it is marked

'shield_tech' and 'defence_tech' is the opposite.

'Shield_tech' => 'defence_tech'
'defence_tech' => 'Shield_tech'

And

111 => armour
110 => shield

What if I modify any part?

**Comment by jstar88** [comment]
i didn't understood at all, however what you need to edit is getTechsFromArray() and getTechsFromArrayForReport() from 2moon implementation
