### ISSUE TITLE
battle engine problem

### ISSUE THREAD

**Issue by a950216t** [jstar88/opbe#23]
Hello I have a question about the mechanism of how the battle engine works on high tier fleet against low tier.
When I stimulated massive basic defence units against the top tier units, I found that no damage can be done on the top tier units and I am very curious about the result.

Example:

Attacker: 100 black moons
Defender: 100 billion light laser turret

Result:
The battle ended in a draw. 
The attacker lost a total of 0 units.
The defender lost a total of 67 214 000 units.

and a message showed up while the battle: 
The defending fleet fires a total of 100'000'000'000 times with the power of 10'000'000'000'000 upon the attacker.
The attacker's shields absorb 0 damage points.

Is that a bug or some special setting for high tier units protection? Many thanks!

**Comment by jstar88** [comment]
The light laser has attack power of 100 while black moon's shield is 70'000.
Since 70'000 / 100 = 700 is more than 100, the bounce effect appear.
http://ogame.wikia.com/wiki/Bouncing_Effect
So, every shots from light lasers will not damage black moon's shield or integrity
