### ISSUE TITLE
each debris percentage for defence and ships

### ISSUE THREAD

**Issue by noonn** [jstar88/opbe#24]
can i settings for per each debris percentage of defence and ships from destroyed resources?

**Comment by jstar88** [comment]
in contants/battle_constants.php 

define('DEBRIS_FACTOR', 0.3);  = 30%, you can set it to 0,5 for example

**Comment by noonn** [comment]
Thanks. But
in contants/battle_constants.php --> define('DEBRIS_FACTOR', 0.3);
This is i know.

I want to specify as follows:
DEFENCE  DEBRIS_FACTOR 0.2%
SHIPS DEBRIS_FACTOR 0.3

Is it possible?

**Comment by jstar88** [comment]
https://github.com/jstar88/opbe/commit/0c519b892684db0e6df46a3dbcf1ec8b69e26fbd
now yes

**Comment by noonn** [comment]
Thanks jstar88 ^^
Sorry, I found Some calculation wrong.
My setting is 
define('SHIP_DEBRIS_FACTOR', 0.3);
define('DEFENSE_DEBRIS_FACTOR', 0.3);

For example.....

Round 1 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1

Defender Defender Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Heavy Laser Turret
10


Round 2 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1

Defender Defender Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Heavy Laser Turret
7


Attacker Losses: 0 units
Defender Losses: 24.000 units
Debris Coords 5.400 Metal and 1.800 Crystal .


This is debris OK OK OK....5.400 Metal and 1.800 Crystal.
=================================


Round 1 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1

Defender Defender Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Light Cargo
10


Round 2 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1


Attacker Losses: 0 units
Defender Losses: 40.000 units
Debris Coords 6.000 Metal and 6.000 Crystal .


This is debris OK OK OK....6.000 Metal and 6.000 Crystal
=======================================


But Light Cargo 10 + Heavy Laser Turret 10 is wrong.


Round 1 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1

Defender Defender Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Light Cargo
10
Heavy Laser Turret 
10


Round 2 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1


Defender Defender Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Heavy Laser Turret
7


Attacker Losses: 0 units
Defender Losses: 64.000 units
Debris Coords 7.200 Metal and 3.600 Crystal .

===========================================
Light Cargo 10 Lost and Heavy Laser Turret 3 Lost
This is debris wrong for 7.200 Metal and 3.600 Crystal.
===========================================

I thinks
5,400 + 6,000 = 11,400 debris Metal is OK.
1,800 + 6000 = 7,800 debris Crystal is OK.

**Comment by jstar88** [comment]
https://github.com/jstar88/opbe/commit/ddf9c01303c41984658ed44cbd4da477bce4f061

**Comment by noonn** [comment]
Hi~~
Also I found Some calculation wrong.
My setting is
define('SHIP_DEBRIS_FACTOR', 0.3);
define('DEFENSE_DEBRIS_FACTOR', 0.3);

For example.....

Round 1 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1

Defender Defender Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Heavy Laser Turret
10

Round 2 :
Attacker Attacker Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Battle Fortress
1

Defender Defender Nr.1 ([1:33:7])
Weapons 100% - Shields 100% - Armour 100%
Heavy Laser Turret
7

Attacker Losses: 0 units
Defender Losses: 24.000 units
Debris Coords 18,000 Metal and 6,000 Crystal .

...18,000 Metal and 6,000 Crystal is wrong.^^
==================================================

**Comment by jstar88** [comment]
1 laser turret = 6000 metal
10 laser turrets = 6000 * 10 metal
debris = 60000 * 0.3 = 18000. // it's correct
