### ISSUE TITLE
Will there be any usage example without 2Moons or Xgp?

### ISSUE THREAD

**Issue by OzanKurt** [jstar88/opbe#25]

**Comment by athk** [comment]
Well I suppose that's a hard thing to do. It's got to be based on a fleet structure, and whatever that fleet structure is, it's implementation dependant. What usage examples would you be looking for precisely?

**Comment by OzanKurt** [comment]
@athk I mean it would be really nice if there were some comments while generating the battle report so that we can read whats going on during the process.

**Comment by jstar88** [comment]
You can set debug active on battle simulator to check everythings.. However this is a bit spammy to use as ingame battle report

**Comment by OzanKurt** [comment]
@jstar88 Will try. Thanks.
