### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Hilarious001** [jstar88/opbe#27]
Hello can you give me the files names i have to edit if i would like example to offer the player the opportunity to have a double attack ? didn't find out exactly, 

Regards

**Comment by jstar88** [comment]
https://github.com/jstar88/opbe/blob/master/core/Round.php

double this line
$this->fire_a->add(new Fire($shipType, $defendersMerged));

**Comment by Hilarious001** [comment]
Thanks alot and one last question how can i call something from the missioncaseattack of 2moons, that i can use on the calculateatack page of OPBE but i want also to use it on the file to adapt the debris generated and the restored defense in function of that players powerups

not only the static value defined in battle constant 
I dont need the code i just want to know how i can use a players info from my database to adapt those 2 functions in BattleReport.php

Example $Players['regenerated_debris_premium']

**Comment by jstar88** [comment]
the easiest solutions is to replace constants like this
if (!defined('SHIP_DEBRIS_FACTOR')) {
    define('SHIP_DEBRIS_FACTOR', 0.3);
}
and define it in 2moon, before call OPBE.
To see what happens in battle report with "premium tech", like you said, you must double a lot of code

**Comment by florin1693** [comment]
Hi! I can't figure out...how units pick their target? Did they just shoots standard shoots vs all kind of units (my unit1/count(enemyTypes))?

**Comment by jstar88** [comment]
it depends: if attacker doesn't has RF then it will shot 1 time, otherwise there is a probability to shot more than 1 based on defender types. I suggest you to check Ogame forum for more infos
