### ISSUE TITLE
Report customization

### ISSUE THREAD

**Issue by LucasKovacs** [jstar88/opbe#28]
@jstar88 This ticket is more a feature request than an issue, but, It will be great to be able to edit the presentation of the combat reports without the need to modify the OPBE library.

Other thing that I notice is that the destroy mission is pretty similar to the attack mission, main differences are that there is no moon creation, no debris, and the script needs to calculate the the chance of moon destruction, death start destruction or the tie.

Any thought about this?

Regards,
lucky

**Comment by XGProyect** [comment]
Another great thing will be to be able to set the amount of fleet and defenses that goes to debris.

**Comment by BeReal86** [comment]
https://github.com/XGProyect/XG-Proyect-v3.x.x/issues/77

**Comment by jstar88** [comment]
hi,
i will check.

> Another great thing will be to be able to set the amount of fleet and defenses that goes to debris.
in constants.php
define('SHIP_DEBRIS_FACTOR', 0.3); //Percentage of debris generated from destroyed defenses.
define('DEFENSE_DEBRIS_FACTOR', 0.3); //Percentage of debris generated from destroyed ships.

**Comment by XGProyect** [comment]
@jstar88 about the constats, I mean a way to configure them without having to make changes in the OPBE core.

Maybe.. you can change the SHIP_DEBRIS_FACTOR and DEFENSE_DEBRIS_FACTOR, putting if is not defined then set those values.

So it will be like this: xgp contants.php file:

define('DEFENSE_DEBRIS_FACTOR', 0.3);

In OPBE battle_constants.php:

if (!defined('DEFENSE_DEBRIS_FACTOR')) {
    define('DEFENSE_DEBRIS_FACTOR', 0.3);
}

**Comment by jstar88** [comment]
good idea
