### ISSUE TITLE
Increase the attack power

### ISSUE THREAD

**Issue by noonn** [jstar88/opbe#35]
Hello. jstar88
How are you?
I have a question.
My 2moons version is 1.3
My english is no good. sorry...^^

From basic attack power... (var.php)

Can I increase the attack power of the Attacker battle_ship + 10% and the Defender's light_hunter attack power + 20% in battle?

The bottom line is that in battle I want to add an increase in attack power to each attacker & defender's fleet or defense facility.

Is it possible?

**Comment by jstar88** [comment]
yes, in core/Battle.php

```
...
//------your code----- $idPlayer is target ID player to increment power, and $idShip is your battle_ship ID (such as 202)
foreach ($this->attackers->getPlayer($idPlayer)->getIterator() as $idFleet => $fleet)
{
         $fleet->getShipType($idShip)->originalPower *= 1.1;
}
//----------------------
...            
//initialize the round
$round = new Round($this->attackers, $this->defenders, $i);
$round->startRound();
```
