### ISSUE TITLE
Battle Engine Error - Undefined index: techs

### ISSUE THREAD

**Issue by bihline** [jstar88/opbe#8]
Hi,
I implemented Your Battle Engine on 2Moons v1.7 script. Your battle module is very good, but has one bug. 
The players can't attack colony planets of other players, and players can't attack inactive user planets. This error shows up:
here is screenshoot:  http://pokit.org/get/img/fae68c241700a8fd9d85105bd1b699f2.jpg

NOTICE
Message: Undefined index: techs
File: /includes/classes/missions/GenerateReport.php
Line: 72
URL: http://bihline.com/game.php?page=overview
PHP-Version: 5.3.28
PHP-API: cgi-fcgi
MySQL-Cleint-Version: 5.1.67
2Moons Version: 1.7.2676
Debug Backtrace:
#0 /includes/classes/missions/GenerateReport.php(72): errorHandler(8, 'Undefined index...', 'FILEPATH ...', 72, Array)
#1 /includes/classes/missions/MissionCaseAttack.php(322): GenerateReport(Array, Array)
#2 /includes/classes/class.FlyingFleetHandler.php(80): MissionCaseAttack->TargetEvent()
#3 /includes/FleetHandler.php(40): FlyingFleetHandler->run()
#4 /includes/common.php(126): require('FILEPATH ...')
#5 /game.php(35): require('FILEPATH ...')
#6 {main} 

How can I fix this. Please help.
Thanks

**Comment by jstar88** [comment]
It's a bit hard to see this. Upload the file and the log.txt as i wrote you in a hosting server

**Comment by AmericaToday** [comment]
you are missing this in calculate attack and it works after you added it
$attackers[$fleetID]['techs'] = array($attTech, $defTech, $shieldTech);
$defenders[$fleetID]['techs'] = array($attTech, $defTech, $shieldTech);

**Comment by jstar88** [comment]
this bug should be fixed with new opbe version, update it
